# Succesful entry
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphcyIsImlkIjoiNWVlYTZkMTUzN2MzOWMwYTJkNzAzOTJkIiwiaWF0IjoxNTkyNDI2NTcyfQ.Y5V_Y4aPYBKukkndvy50bRY-dD8Jac1Q-lHksjpUjBw

{
    "title": "I never heard about the big strong man",
    "author": "John",
    "url": "second-blog-post",
    "likes": 9
}